services:
  - type: web
    name: todo-app
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: gunicorn base.wsgi:application --bind 0.0.0.0:${PORT:-8000}
